# Generated by Django 2.2.7 on 2020-05-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legopart',
            name='official_ids',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='legopart',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='legoset',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
