# Generated by Django 3.0.6 on 2020-05-25 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='set_id',
            new_name='lego_set',
        ),
    ]
