# Generated by Django 3.0.6 on 2020-05-19 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setpart',
            old_name='color_id',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='setpart',
            old_name='set_id',
            new_name='lego_set',
        ),
        migrations.RenameField(
            model_name='setpart',
            old_name='part_id',
            new_name='part',
        ),
    ]
