# Generated by Django 3.0.6 on 2020-05-21 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200519_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legoset',
            old_name='image',
            new_name='images',
        ),
    ]
