# Generated by Django 3.0.6 on 2020-05-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200525_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='review_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='legoset',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
