# Generated by Django 3.0.6 on 2020-06-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userset'),
    ]

    operations = [
        migrations.AddField(
            model_name='legoset',
            name='sub_set',
            field=models.ManyToManyField(blank=True, null=True, related_name='_legoset_sub_set_+', to='api.LegoSet'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(default=0),
        ),
    ]
