# Generated by Django 2.2.7 on 2020-05-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200515_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legoset',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='officialmapping',
            name='official_id',
            field=models.CharField(max_length=50),
        ),
    ]
