# Generated by Django 2.2.7 on 2020-05-15 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200515_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legopart',
            old_name='category_id',
            new_name='category',
        ),
    ]
