# Generated by Django 3.0.6 on 2020-05-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200528_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='legoset',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
