# Generated by Django 3.0.6 on 2020-05-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_legoset_like_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLikeLegoSet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'api_legoset_like_users',
                'managed': False,
            },
        ),
    ]
