# Generated by Django 2.2.7 on 2020-05-15 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200515_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legoset',
            old_name='images',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='officialmapping',
            name='official_id',
        ),
        migrations.RemoveField(
            model_name='officialmapping',
            name='set_id',
        ),
        migrations.AddField(
            model_name='officialmapping',
            name='lego_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.LegoSet'),
        ),
        migrations.AlterField(
            model_name='legoset',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='officialmapping',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
