# Generated by Django 3.0.6 on 2020-05-28 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userlikelegoset'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPart2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Color')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LegoPart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
