# Generated by Django 3.0.6 on 2020-05-28 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userpart2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpart2',
            name='quantity',
        ),
    ]
