# Generated by Django 2.2.7 on 2020-05-15 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200515_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legoset',
            old_name='theme_id',
            new_name='theme',
        ),
    ]
