# Generated by Django 3.0.6 on 2020-06-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_userpart2_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='categories',
            field=models.TextField(null=True),
        ),
    ]
