# Generated by Django 2.2.7 on 2020-05-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200515_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='legoset',
            name='num_parts',
            field=models.IntegerField(null=True),
        ),
    ]
