# Generated by Django 3.0.6 on 2020-06-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customuser_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='root_id',
            field=models.IntegerField(null=True),
        ),
    ]
